### ISSUE TITLE
[Migration] Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:

### ISSUE THREAD

**Issue by HAMADOns** [MikeCodeur/typescript-patterns#3]
au lancement de l'exo 1 le terminal affiche le warning suivant :

<img width="587" alt="image" src="https://github.com/user-attachments/assets/96055485-d2c5-418e-af68-b283840e096b">

✓ Compiled /alone/solution/[solutionId] in 660ms (1607 modules)
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.       
 ⨯ Internal error: TypeError: Cannot read properties of null (reading 'useContext')
    at t.useContext (C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:163120)
    at usePathname (./node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/client/components/navigation.js:122:34)
    at ErrorBoundary (./node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/client/components/error-boundary.js:129:50)
    at ai (C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:6505)
    at C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:11284
    at ab (C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:13038)
    at e (C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:46298)
    at aS (C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:48276)
    at ag (C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:7923)
    at C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:13014
    at ab (C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:13038)
    at ab (C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:43088)
    at e (C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:46298)
    at aS (C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:48276)
    at a_ (C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:50165)
    at ak (C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:49406)
    at e (C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:46647)
    at aS (C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:48276)
    at e (C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:46613)
    at aS (C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:48276)
    at C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:55195
    at C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:55862
    at a$ (C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:55870)
    at Timeout._onTimeout (C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:4037)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.       
TypeError: Cannot read properties of null (reading 'useContext')
    at t.useContext (C:\Users\onsha\Desktop\FINALISATION - MIGRATION REACT\course-app\node_modules\.pnpm\next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:163120)
    at usePathname (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/client/components/navigation.js:122:34)  
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/client/components/error-boundary.js:129:50)

**Comment by HAMADOns** [comment]
ça ne s'affiche pas tout le temps, il  faut seulement un nettoyage de cash ou seppression du dossier next et relancer l'app
